### ISSUE TITLE
WoW Client hangs when loading AppearanceTooltip with other AddOns

### ISSUE THREAD

**Issue by Beet4** [kemayo/wow-appearancetooltip#22]
Since the pre-patch when loading into the game my client renders a few frames then completely hangs when this AppearanceTooltip is loaded together with my other addons. I've tried to have it waiting for up to 10 minutes without any success, I have to forcefully quite the client. Once I unload AppearanceTooltip it works fine. But if I only load AppearanceTooltip it works as expected.

Did something change in the pre-patch so the addon has to load a lot more assets or something? 

[This commit](https://github.com/kemayo/wow-appearancetooltip/commit/23baf5cc9fd0e9ee0b05761e9e671890890eb49d) did not change anything for me, unfortunately.

**Comment by kgns** [comment]
this happens on my remix char, but not my retail chars, hopefully might help debugging

**Comment by kemayo** [comment]
...interesting, for me that did stop it. It's probably really dependent on details of what your character knows.

**Comment by kemayo** [comment]
Would you mind trying the alpha that'll come out from that commit and let me know whether it helps?

**Comment by Beet4** [comment]
The new alpha did help some! Without Zygor AddOn loaded it worked fine but with it it hung the same way. I know Zygor takes quite long time to load as well that was why I tried disabling just that addon as well. It did not help to unload just Zygor before this commit so it is some progress.

**Comment by kgns** [comment]
last alpha solved my problem (im not using Zygor)

**Comment by kgns** [comment]
wait, it did not. I tried with another remix char, it did not freeze, but with the one I was experiencing the freeze, it's still freezing

**Comment by kgns** [comment]
I believe there might be some kind of race condition happening with something else, because now even the char the alpha worked is not working (keeps freezing after a few frames on login)

**Comment by kgns** [comment]
yeah, sometimes it happens sometimes it does not, there is a randomness to it, you might be able to replicate it using a remix char and logging in and out until it happens

**Comment by kemayo** [comment]
Okay, good news. It looks like the whole scan-and-cache deal on-game-entry isn't needed now. It *used* to be necessary because you couldn't get a list of appearance sources for items that weren't available for your current class, so if you wanted to know "you know this appearance, but not from *this* item" you had to store that data from times you were logged in as a class that could use it.

I've done some testing, and it looks like (presumably because of Warbands), you can now get that appearance list. As such, I can strip out all that caching-and-saving code and not need to do a big scan when you log in. Technically it'll cause slightly more data usage every time we have to check an item, but it's not actually very much so it should be fine.

**Comment by kemayo** [comment]
Could you confirm that this next alpha (a) doesn't lock up, and (b) doesn't obviously appear to be blatantly incorrect about known/unknown items? (You should be able to compare the status at the bottom of the 3d model to the one written in blue inside the item tooltip, which comes directly from Blizzard.)

**Comment by kgns** [comment]
I checked a few situations like different class tier item, different armor type, weapon type that cannot be used with the current class etc. all of them shows correct information, and since the scan is removed, no more freezes either. LGTM 🚀

**Comment by kemayo** [comment]
Thanks!
